spring:
  datasource:
    url: jdbc:mysql://mysql:3306/api_caderneta_database?useTimezone=true&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000